In [2]:
import numpy as np

In [8]:
arr1=np.array([[1,2],[2,3],[5,6]])
arr2=np.array([[6,8],[5,4],[5,6]])

In [9]:
type(arr2)

numpy.ndarray

In [10]:
arr1+arr2

array([[ 7, 10],
       [ 7,  7],
       [10, 12]])

In [13]:
print(np.sin(arr1))
print(np.cos(arr2))


[[ 0.84147098  0.90929743]
 [ 0.90929743  0.14112001]
 [-0.95892427 -0.2794155 ]]
[[ 0.96017029 -0.14550003]
 [ 0.28366219 -0.65364362]
 [ 0.28366219  0.96017029]]


In [14]:
np.sum(arr1)

np.int64(19)

In [15]:
np.std(arr1)

np.float64(1.7716909687891083)

In [16]:
np.std(arr2)

np.float64(1.247219128924647)

In [38]:
a=np.delete(arr1,1,axis=0)
b=np.delete(arr2,1,axis=0)

In [41]:

import numpy as np

# Two vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Dot product
dot_prod = np.dot(a, b)

# Norm (magnitude) of each vector
norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)

# Compute cosine of the angle
cos_theta = dot_prod / (norm_a * norm_b)

# Now get angle in radians
theta_rad = np.arccos(cos_theta)

# Convert to degrees (optional)
theta_deg = np.degrees(theta_rad)

print(f"Angle in radians: {theta_rad}")
print(f"Angle in degrees: {theta_deg}")


Angle in radians: 0.2257261285527342
Angle in degrees: 12.933154491899135


In [40]:
%%manim -qm -v WARNING VectorAngle

from manim import *
import numpy as np

class VectorAngle(Scene):
    def construct(self):
        # Axes for X-Y plane
        axes = Axes(
            x_range=[-1, 9, 1],
            y_range=[-1, 3, 1],
            axis_config={"color": GREY}
        )
        self.play(Create(axes))

        # Define vectors in 2D
        a = np.array([5, 9, 0])
        b = np.array([8, 7, 0])

        # Arrows from origin
        vec_a = Arrow(ORIGIN, a, buff=0, color=BLUE)
        vec_b = Arrow(ORIGIN, b, buff=0, color=GREEN)

        self.play(Create(vec_a), Create(vec_b))

        # Dot at vector heads
        dot_a = Dot(a, color=BLUE).scale(0.8)
        dot_b = Dot(b, color=GREEN).scale(0.8)

        # Label with coordinates
        label_a = MathTex("(1, 2)").next_to(dot_a, RIGHT + UP, buff=0.2)
        label_b = MathTex("(3, 5)").next_to(dot_b, RIGHT + UP, buff=0.2)

        self.play(FadeIn(dot_a), Write(label_a))
        self.play(FadeIn(dot_b), Write(label_b))

        # Calculate and show angle
        dot_product = np.dot(a[:2], b[:2])
        norm_a = np.linalg.norm(a[:2])
        norm_b = np.linalg.norm(b[:2])
        cos_theta = dot_product / (norm_a * norm_b)
        angle_rad = np.arccos(cos_theta)
        angle_deg = np.degrees(angle_rad)

        angle_arc = Angle(vec_a, vec_b, radius=0.7, color=YELLOW)
        angle_label = MathTex(f"{angle_deg:.2f}^\\circ").next_to(angle_arc, UP, buff=0.1)

        self.play(Create(angle_arc), Write(angle_label))
        self.wait(2)


Manim Community v0.19.0

In [58]:
%%manim -qm -v WARNING LinearRegressionFull

from manim import *
import numpy as np

class LinearRegressionFull(Scene):
    def construct(self):

        # 1. Title
        title1 = Text("Welcome to part 2 of Linear Regression Made easy")
        self.play(Write(title1))
        self.play(title1.animate.to_edge(UP))
        self.play(FadeOut(title1))

        # 2. Show equation y = mx + c
        title = MathTex("y = mx + c")
        self.play(Write(title))
        self.play(title.animate.to_edge(UP))

        # 3. Axes
        axes = Axes(
            x_range=[0, 6], y_range=[0, 6],
            x_length=6, y_length=4,
            axis_config={"include_numbers": True}
        ).to_edge(DOWN)
        labels = axes.get_axis_labels("x", "y")
        self.play(Create(axes), Write(labels))

        # 4. Sample data points
        data_points = [(1, 2), (2, 2.5), (3, 3.3), (4, 4), (5, 4.2)]
        dots = VGroup(*[Dot(axes.coords_to_point(x, y), color=YELLOW) for x, y in data_points])
        self.play(FadeIn(dots))

        # 5. Bad initial line
        bad_line = axes.plot(lambda x: 0.5 * x + 1, color=BLUE)
        self.play(Create(bad_line))
        self.wait(1)

        # 6. Error lines
        error_lines = VGroup()
        for x, y_actual in data_points:
            y_pred = 0.5 * x + 1
            err_line = DashedLine(
                start=axes.coords_to_point(x, y_actual),
                end=axes.coords_to_point(x, y_pred),
                color=RED
            )
            error_lines.add(err_line)
        self.play(Create(error_lines))

        # 7. Cost function formula
        cost_formula = MathTex("J(m) = \\frac{1}{n} \\sum (y_{pred} - y)^2").next_to(axes, DOWN)
        self.play(Write(cost_formula))
        self.wait(1)

        # 8. Cost Curve
        self.clear()
        title2 = MathTex("J(m) = \\text{Cost for different slopes}").to_edge(UP)
        self.play(Write(title2))

        m_values = [i * 0.1 for i in range(-10, 21)]  # from -1.0 to 2.0

        def compute_cost(m):
            return sum([(m * x - y) ** 2 for x, y in data_points]) / len(data_points)

        cost_values = [compute_cost(m) for m in m_values]

        cost_axes = Axes(
            x_range=[-1, 2, 0.5], y_range=[0, 5, 1],
            x_length=8, y_length=4,
            axis_config={"include_numbers": True}
        ).to_edge(DOWN)

        cost_graph = cost_axes.plot_line_graph(
            x_values=m_values, y_values=cost_values,
            add_vertex_dots=False, line_color=BLUE
        )
        m_label = cost_axes.get_x_axis_label("m")
        j_label = cost_axes.get_y_axis_label("J(m)")
        self.play(Create(cost_axes), Write(m_label), Write(j_label))
        self.play(Create(cost_graph))
        self.wait(1)

        # 9. Gradient descent
        slope = 1.8
        dot = Dot(cost_axes.coords_to_point(slope, compute_cost(slope)), color=RED)
        self.play(FadeIn(dot))

        learning_rate = 0.05  # lowered to prevent divergence
        for _ in range(6):
            grad = self.compute_gradient(slope, data_points)
            slope -= learning_rate * grad
            new_pos = cost_axes.coords_to_point(slope, compute_cost(slope))
            self.play(dot.animate.move_to(new_pos), run_time=0.5)

        self.wait(1)

        # 10. Final line after learning
        self.clear()
        final_title = MathTex("y = mx + c \\quad \\text{(after learning)}").to_edge(UP)
        self.play(Write(final_title))

        final_axes = Axes(
            x_range=[0, 6], y_range=[0, 6],
            x_length=6, y_length=4,
            axis_config={"include_numbers": True}
        ).to_edge(DOWN)
        labels = final_axes.get_axis_labels("x", "y")
        self.play(Create(final_axes), Write(labels))

        final_dots = VGroup(*[Dot(final_axes.coords_to_point(x, y), color=YELLOW) for x, y in data_points])
        self.play(FadeIn(final_dots))

        # 11. Final learned line
        best_m = slope
        best_c = self.compute_best_c(best_m, data_points)

        # Print for debugging
        print(f"Best slope (m): {best_m}")
        print(f"Best intercept (c): {best_c}")

        final_line = final_axes.plot(
            lambda x: best_m * x + best_c,
            color=GREEN
        )
        self.play(Create(final_line))

        # Optional: show the equation
        equation = MathTex(f"y = {round(best_m, 2)}x + {round(best_c, 2)}")
        equation.next_to(final_line, UP)
        self.play(Write(equation))

        self.wait(2)

        self.play(FadeOut(final_title, final_dots, final_line, equation,final_axes,labels))

        greet=Text("Thank you for watching!").to_edge()
        self.play(Write(greet))
        self.wait(2)
        self.play(FadeOut(greet))

    def compute_gradient(self, m, points):
        n = len(points)
        grad = sum([2 * x * (m * x - y) for x, y in points]) / n
        return grad

    def compute_best_c(self, m, points):
        residuals = [y - m * x for x, y in points]
        return sum(residuals) / len(residuals)


Manim Community v0.19.0

Best slope (m): 0.98000082
Best intercept (c): 0.25999753999999997
